### ISSUE TITLE
Spacebar issues in Linux

### ISSUE THREAD

**Issue by IiroP** [lehtoroni/lmath-issues#33]
When switching between apps/virtual desktops, L'Math occasionally starts to act weirdly. Spacebar won't insert space, but instead opens the calculator. 

Workaround is to either close the window or to resize the window. These usually work, but not always.

(Using Arch Linux with i3 window manager)

**Comment by lehtoroni** [comment]
> When switching between apps/virtual desktops, L'Math occasionally starts to act weirdly. Spacebar won't insert space, but instead opens the calculator.

Since the shortcut for opening the calculator is Shift+SPACE (and it's captured inside the browser window), pressing down shift while focused to L'Math and then releasing the shift key after having L'Math unfocused can lead to this situation.

The quick way to get over this is to press the shift key or the Shift+SPACE shortcut repeatedly for a few times. This problem is known, and will be fixed in a future release.

**Comment by lehtoroni** [comment]
> > When switching between apps/virtual desktops, L'Math occasionally starts to act weirdly. Spacebar won't insert space, but instead opens the calculator.
> 
> Since the shortcut for opening the calculator is Shift+SPACE (and it's captured inside the browser window), pressing down shift while focused to L'Math and then releasing the shift key after having L'Math unfocused can lead to this situation.
> 
> The quick way to get over this is to press the shift key or the Shift+SPACE shortcut repeatedly for a few times. This problem is known, and will be fixed in a future release.

Woops, the shortcut is actually LCtrl+SPACE. Sorry for giving out wrong information.

**Comment by lehtoroni** [comment]
[Will be fixed in r1.6](https://github.com/lehtoroni/lmath/commit/6b6655e3f9130868d991dd10c7bb2dfdb6591036)

> #33; Laskinpikanäppäimen kuuntelija resetoidaan, kun ikkuna ei ole enää aktiivinen

**Comment by lehtoroni** [comment]
(I did it again, let's not close this yet)
