### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Theelevinr** [lehtoroni/lmath-issues#37]
![Picture1](https://user-images.githubusercontent.com/87331348/133029770-1950b8d3-0e96-41cb-af7c-b32175222f88.png)

Error occurs on every startup and started completely arbitrarily without any update or change to the program.

**Comment by Theelevinr** [comment]
Here's the index.js file that the error is pointing to, if any more files are needed, just let me know and I'll post them here.
[index.txt](https://github.com/lehtoroni/lmath-issues/files/7151772/index.txt)
(Note the file is in txt format due to github filetype support)

**Comment by Theelevinr** [comment]
After some debugging I found out that the error is caused by the 3rd party plugins option in the settings. When toggling the option on, the error occurs in the next boot. If the value is modified to false in the settings.json file, the issue gets resolved.

**Comment by DanyaChan** [comment]
What about on MacBooks ? I have pretty same problem, but I don't know how to toggle the switch off, because I can't open the app itself. What file is an alternative to the settings.json on Macbooks ?

<img width="256" alt="image" src="https://user-images.githubusercontent.com/32737124/144200143-dc5293a7-9413-4f45-a021-a45f2f443c1f.png">

**Comment by lehtoroni** [comment]
As stated earlier, 3rd party plugin support (without any installed plugins in the plugins folder) will cause this crash.

The first-hand solution is to empty the data folder (`%APPDATA%\LMath` or `~/Library/Application Support/LMath` or `~/.local/share/LMath`), or delete the json files (at least), or to manually disable plugin support from `settings.json` and `user.json`.

This will be fixed in r1.8 (and the pre-release version r1.8_pre1, which will be available today).

**Comment by lehtoroni** [comment]
**Note:** This has now been fixed in the latest production version update (r1.8)
