### ISSUE TITLE
 Files are loading as broken r1.10.7 

### ISSUE THREAD

**Issue by lindkon** [lehtoroni/lmath-issues#80]
Editing files works for my computer (macOS13.6.3). However when I try to load any saved file the error "No page data for loaded page ?" pops up. The page title is set as "Broken worksheet init page". Fixing the page using the online tool does not work.

**Comment by lehtoroni** [comment]
Ah, I've been waiting for this issue to reappear. The same happened with macOS autoupdate 1.10.6.

Could @lindkon please answer these questions:
- Does your Mac have an M1/M2/M3 (ARM-based) CPU?
- Did L'Math download an autoupdate before the issue occurred?
- If, then do you remember the original L'Math version that you had installed?

The issue can be fixed by navigating to ~/Library/Application Support/ (e.g. with Finder => Go => Go to folder), and removing the lmath-bootstrap folder. Then, if you manually download the latest version, everything should work again.

If possible, could you please compress the said lmath-bootstrap folder (before deleting it) and send it to me via email as a zip file? (roni.lehto -at- lehtodigital.fi)

**Comment by lehtoroni** [comment]
This might be fixed in the release 1.10.8. Waiting for confirmation from Mac users.

**Comment by lehtoroni** [comment]
I assume the recent fixes in 1.10.8 (fixed noAsar being left to true) and 1.10.9 (fixed åäö breaking MathJax-node) have fixed this. Please reopen if the issue still persists after updating (manually or automatically) to 1.10.8.

**Comment by lindkon** [comment]
Yes, thank you!
